### PR TITLE
Add mkstats

### PR DESCRIPTION
**Pull request by jkarner**
Add the mkstats tool from github.com/jsha/ to
the SRE-tools repository for future iterations
preserving the previous commit history

### CODE REVIEW

**Comment by jkarner** [comment]
Travis errors, planning to re-open

**Review by aarongable — APPROVED** [review]

**Comment by beautifulentropy** [comment]
Went looking for mkstats in sre-tools and I'm seeing this PR is still open. Did you need another set of eyes on the build failure @jkarner?

**Comment by jkarner** [comment]
> Went looking for mkstats in sre-tools and I'm seeing this PR is still open. Did you need another set of eyes on the build failure @jkarner?

It's not merged because I was hoping to fix the `golangci-lint` errors. I can merge if I remove some of the branch requirements.

**Comment by aarongable** [comment]
A rebase of this should now pick up the .golangci.yaml which just landed, and should be green. (Don't merge master into this branch, as that'll make the history all sorts of ugly. Just do the whole merge-from-FETCH_HEAD part of of the process again, and force-push the PR branch.)

**Review by beautifulentropy — APPROVED** [review]

**Comment by beautifulentropy** [comment]
Yay! Feel free to merge once Travis gives us the 💯

**Review by aarongable — APPROVED** [review]

**Pull request merged**
